name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      - 
        name: Set env
        # use hint from this stackoverflow answer https://stackoverflow.com/a/65130107/13360987
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jgero
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # the setting in github from this comment was needed to make it work: https://github.com/docker/build-push-action/issues/205#issuecomment-728894085
          push: true
          tags: ghcr.io/jgero/latex-container/compile-latex-container:${{ env.GIT_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
